<div class="markupHelp">
<pre>
~~~~~~~~
# Section heading

## Subsection

Formatting:  *italics*,
**bold**, super^script^,
sub~script~, ~~strikeout~~.

A line break  
can be forced with two spaces
at the end of the line.

> Indented quotation

Links:
[external](http://google.com),
[Wiki Link](),
![image](/img/gitit-banner.png),
[to heading](#section-heading).

Reference-style links:
[Link Text][keyword]

[keyword]: http://chea.niltag.net

Unformatted text:

    Indent 4 spaces
    to get unformatted
    text

## Lists!

- bulleted
- list

* * * * *

1.  ordered
2.  list
    a. sublist (indent 4 spaces)
    b. another
3.  item three

term
:   definition
orange
:   orange fruit

~~~~~~~~

For more: [markdown syntax](http://daringfireball.net/projects/markdown),
[pandoc extensions](http://johnmacfarlane.net/pandoc/README.html).


</pre>
</div>
